theme: jekyll-theme-minimal
title: Guide to hats-ci
description: >
  <a href="#section-1">Installing hats-ci</A>
  <br><br>
  <a href="#section-2">Running hats-ci</A>
  <br><br>
  <a href="#section-3">Android Automation using Appium</A> 
  <br><br>
  <a href="#section-4">Browser Automation using Robotcorder</A> 
