theme: jekyll-theme-minimal
title: Guide to hats-ci
description: >
  <a href="#section-1">Installing hats-ci</A>
  <br><br>
  <a href="#Running-hats-ci">Running hats-ci</A>
  <br><br>
  <a href="#Android-Automation-using-Appium">Android Automation using Appium</A> 
  <br><br>
  <a href="#Browser-Automation-using-Robotcorder">Browser Automation using Robotcorder</A> 
