theme: jekyll-theme-minimal
title: Guide to hats-ci
description: >
  Installing hats-ci
  <br><br>
  Running hats-ci
  <br><br>
  Android Automation using Appium 
  <br><br>
  Browser Automation using Robotcorder
  <br><br>
  
  
